### PR TITLE
add chinese traditional localizational(zh-Hant.lproj)

### PR DESCRIPTION
**Pull request by powenn**

### CODE REVIEW

**Comment by Lakr233** [comment]
I'll merge this later when I finish the UI design. :)

**Comment by powenn** [comment]
> I'll merge this later when I finish the UI design. :)

Got it, thanks for response

**Comment by Lakr233** [comment]
Hi there, I have create an updated Localizable.strings file for you. You may want to checkout newer commit and create i18n patch from that commit.

[Localizable.strings.zip](https://github.com/SailyTeam/Saily/files/7175546/Localizable.strings.zip)

Make sure to run `bartycrouch update` for a validated format, or send strings file back to me and I'll do that. Thanks for your time.

**Comment by powenn** [comment]
> Hi there, I have create an updated Localizable.strings file for you. You may want to checkout newer commit and create i18n patch from that commit.
> 
> 
> 
> [Localizable.strings.zip](https://github.com/SailyTeam/Saily/files/7175546/Localizable.strings.zip)
> 
> 
> 
> Make sure to run `bartycrouch update` for a validated format, or send strings file back to me and I'll do that. Thanks for your time.


Understand it,actually I saw your tweet that solved UI,and I check updated source code this morning, I will update strings when back home,thanks for mention me

**Pull request closed without merging**
