### PR TITLE
Update several strings of zh-Hant

### PR DESCRIPTION
**Pull request by powenn**

### CODE REVIEW

**Comment by Lakr233** [comment]
I have merged string from Crowdin, do I still need to merge this?

**Comment by powenn** [comment]
> I have merged string from Crowdin, do I still need to merge this?

Yes,some strings modified last night,but wait me solve conflicts, I will mention you while solved,thx

**Comment by powenn** [comment]
> I have merged string from Crowdin, do I still need to merge th

**Comment by powenn** [comment]
@Co2333 conflicts solved,can merge it,thx 😉

**Comment by Lakr233** [comment]
Squash Merged 58276bb, thx.

**Pull request closed without merging**
